# Generated by Django 4.2.11 on 2024-08-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('m', 'Dr.'), ('f', 'Dra.')], max_length=1)),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('cro', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('m', 'ele/dele'), ('f', 'ela/dela')], max_length=1)),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('funcao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d0', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=300)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('dentistas', models.ManyToManyField(blank=True, to='consultorio.dentista')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('rua', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=70, null=True)),
                ('cidade', models.CharField(default='Três Corações', max_length=200)),
                ('estado', models.CharField(default='MG', max_length=2)),
                ('pais', models.CharField(default='Brasil', max_length=50)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(default='55', max_length=3)),
                ('ddd', models.CharField(default='35', max_length=2)),
                ('numero', models.CharField(max_length=9)),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('celular', 'celular'), ('fixo', 'telefone fixo'), ('trabalho', 'trabalho')], default='whatsapp', max_length=10)),
                ('obs', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letras', models.CharField(max_length=2)),
                ('ordem', models.PositiveIntegerField(blank=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo', to='consultorio.paciente')),
            ],
            options={
                'ordering': ['letras', 'ordem'],
            },
        ),
    ]
