# Generated by Django 4.2.11 on 2024-08-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
    ]
