# Generated by Django 4.2.11 on 2024-08-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0002_codigo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='numero',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
