# Generated by Django 4.2.11 on 2024-09-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0003_alter_contato_numero_alter_endereco_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='obs',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='pais',
        ),
    ]
