# Generated by Django 4.2.11 on 2024-09-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0004_rename_obs_contato_nome_remove_contato_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('celular', 'celular'), ('fixo', 'fixo'), ('trabalho', 'trabalho')], default='whatsapp', max_length=10),
        ),
    ]
