# Generated by Django 4.2.11 on 2024-06-10 17:35

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_ps_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ps',
            options={'ordering': ['-u0']},
        ),
        migrations.AlterModelOptions(
            name='tg',
            options={'ordering': [django.db.models.functions.text.Lower('tag')]},
        ),
        migrations.AlterField(
            model_name='ps',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='link original ativo'),
        ),
        migrations.AlterField(
            model_name='ps',
            name='link',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='ps',
            name='link2',
            field=models.URLField(blank=True, help_text='link do <a class="txt" href="https://web.archive.org/">internet archive</a> se o link original estiver indisponível', max_length=400, verbose_name='internet archive'),
        ),
        migrations.AlterField(
            model_name='ps',
            name='obs',
            field=models.TextField(blank=True, verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='ps',
            name='tags',
            field=models.ManyToManyField(blank=True, to='links.tg'),
        ),
        migrations.AlterField(
            model_name='ps',
            name='titulo',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
