# Generated by Django 4.2.11 on 2024-06-04 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zanine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['ano', 'mes', 'dia']},
        ),
        migrations.AddField(
            model_name='data',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_pt', models.TextField(blank=True, null=True)),
                ('info_fr', models.TextField(blank=True, null=True)),
                ('fim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fim', to='zanine.data')),
                ('inicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zanine.data')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zanine.tag')),
            ],
            options={
                'ordering': ['inicio'],
            },
        ),
    ]
