# Generated by Django 4.2.11 on 2024-06-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zanine', '0002_tag_alter_data_options_data_info_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(choices=[('br', 'Brasil'), ('fr', 'França')], default='br', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='nome',
            field=models.SlugField(max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zanine.local'),
        ),
    ]
