# Generated by Django 4.2.11 on 2024-06-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanine', '0003_local_alter_tag_nome_evento_cidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['cidade', 'inicio']},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('order',)},
        ),
        migrations.RenameField(
            model_name='local',
            old_name='cidade',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='local',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='local',
            name='pais',
            field=models.CharField(choices=[('BR', 'Brasil'), ('FR', 'França')], default='BR', max_length=2),
        ),
    ]
