# Generated by Django 4.2.11 on 2024-06-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zanine', '0004_alter_evento_options_alter_local_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='nome',
            new_name='cidade',
        ),
    ]
