# Generated by Django 4.2.11 on 2024-06-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanine', '0006_alter_local_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='d0',
            field=models.CharField(default='0000/00/00', help_text='definir data nos modelos aaaa/mm/dd, aaaa/mm ou aaaa', max_length=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='d1',
            field=models.CharField(blank=True, default='0000/00/00', help_text='definir data nos modelos aaaa/mm/dd, aaaa/mm ou aaaa', max_length=10, null=True),
        ),
    ]
