# Generated by Django 4.2.11 on 2024-06-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zanine', '0007_evento_d0_evento_d1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='d0',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='d1',
        ),
    ]
