# Generated by Django 4.2.11 on 2024-06-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanine', '0008_remove_evento_d0_remove_evento_d1'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='d0',
            field=models.CharField(default=0, help_text='definir como aaaa/mm/dd, aaaa/mm ou aaaa \n>>> data do inicio de um periodo \n>>> ou data de evento pontual', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='d1',
            field=models.CharField(blank=True, help_text='definir como aaaa/mm/dd, aaaa/mm ou aaaa \n>>> data do fim de um periodo \n>>> deixar em branco caso seja um evento pontual', max_length=10, null=True),
        ),
    ]
