# Generated by Django 4.2.11 on 2024-06-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanine', '0015_variaveis_alter_evento_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variaveis',
            old_name='linha',
            new_name='altura',
        ),
        migrations.RemoveField(
            model_name='variaveis',
            name='coluna',
        ),
        migrations.AddField(
            model_name='variaveis',
            name='fonte',
            field=models.CharField(default='Courier', help_text='nome da fonte', max_length=100),
        ),
        migrations.AddField(
            model_name='variaveis',
            name='largura',
            field=models.IntegerField(default=13, help_text='somente números <br> largura (em px) da coluna de cada ano da timeline '),
        ),
        migrations.AlterField(
            model_name='variaveis',
            name='padrao',
            field=models.BooleanField(default=True, help_text='define estas variaveis como padrão para o desenho da timeline'),
        ),
    ]
