# Generated by Django 4.2.11 on 2024-06-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zanine', '0016_rename_linha_variaveis_altura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='cor',
            name='rgb',
            field=models.CharField(help_text='>>> separar valores com espaço <br>rgb = 0-255 0-255 0-255 <br>cinza = 0-255 <br>', max_length=15),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fim',
            field=models.CharField(blank=True, help_text='aaaa/mm/dd ou aaaa/mm ou aaaa <br>>>> data do fim de um periodo <br>>>> deixar em branco caso seja um evento pontual', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='inicio',
            field=models.CharField(help_text='aaaa/mm/dd ou aaaa/mm ou aaaa <br>>>> data do inicio de um periodo <br>>>> ou data de evento pontual', max_length=10),
        ),
        migrations.AlterField(
            model_name='variaveis',
            name='fim',
            field=models.IntegerField(default=2060, help_text='ano <br> fim da timeline'),
        ),
    ]
