# Generated by Django 4.2.11 on 2024-06-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zanine', '0017_alter_local_options_alter_cor_rgb_alter_evento_fim_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variaveis',
            new_name='Variavel',
        ),
    ]
