# Generated by Django 4.2.11 on 2024-06-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zanine', '0019_alter_cor_options_alter_local_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Local',
            new_name='Cidade',
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['id']},
        ),
    ]
