# Generated by Django 4.2.11 on 2024-06-13 20:04

from django.db import migrations, models
import zanine.models


class Migration(migrations.Migration):

    dependencies = [
        ('zanine', '0020_rename_local_cidade_alter_cidade_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['ordem', 'id']},
        ),
        migrations.AddField(
            model_name='tag',
            name='ordem',
            field=models.IntegerField(default=0, help_text=zanine.models.Tag.ordena),
        ),
    ]
